export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const STARTLOADER = "STARTLOADER";
export const STOPLOADER = "STOPLOADER";
export const SETMSG = "SETMSG";
export const CLRMSG = "CLRMSG";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// quiz
export const QUIZ_DETAILS_SUCCESS = "QUIZ_DETAILS_SUCCESS";
export const SET_CUR_QUES = "SET_CUR_QUES";
export const SET_RESPONSE = "SET_RESPONSE";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const SET_QUES_STATUS = "SET_QUES_STATUS";
export const START_TIMER = "START_TIMER";
export const SET_ELAPSED_TIME = "SET_ELAPSED_TIME";

// test
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_SUB_CATEGORIES_SUCCESS = "GET_SUB_CATEGORIES_SUCCESS";
export const CLEAR_SUB_CATEGORIES = "CLEAR_SUB_CATEGORIES";
export const GET_PREVIOUS_TESTS_SUCCESS = "GET_PREVIOUS_TESTS_SUCCESS";

//report
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
