export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const STARTLOADER = "STARTLOADER";
export const STOPLOADER = "STOPLOADER";
export const SETMSG = "SETMSG";
export const CLRMSG = "CLRMSG";
export const SET_ERRORS = "SET_ERRORS";

// quiz
export const QUIZ_DETAILS_SUCCESS = "QUIZ_DETAILS_SUCCESS";
export const SET_CUR_QUES = "SET_CUR_QUES";
export const SET_RESPONSE = "SET_RESPONSE";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const SET_QUES_STATUS = "SET_QUES_STATUS";

// test
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_SUB_CATEGORIES_SUCCESS = "GET_SUB_CATEGORIES_SUCCESS";
export const CLEAR_SUB_CATEGORIES = "CLEAR_SUB_CATEGORIES";
